"""paquetes y config

Revision ID: 00d1f4f97ba9
Revises: cab77db53d96
Create Date: 2026-10-08 13:29:11.733062

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00d1f4f97ba9"
down_revision: str | Sequence[str] | None = "cab77db53d96"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "config",
        sa.Column("clave", sa.Text(), nullable=False),
        sa.Column("valor", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("clave", name=op.f("pk_config")),
    )
    op.create_table(
        "paquetes",
        sa.Column("paquete_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("juego", sa.Text(), nullable=False),
        sa.Column("nombre", sa.Text(), nullable=False),
        sa.Column("diamantes", sa.Integer(), nullable=True),
        sa.Column("precio_costo", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("precio_venta", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("activo", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "actualizado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "activo = false OR precio_venta IS NOT NULL", name=op.f("ck_paquetes_activo_con_precio")
        ),
        sa.CheckConstraint("precio_costo >= 0", name=op.f("ck_paquetes_precio_costo_no_negativo")),
        sa.CheckConstraint(
            "precio_venta IS NULL OR precio_venta > 0",
            name=op.f("ck_paquetes_precio_venta_positivo"),
        ),
        sa.PrimaryKeyConstraint("paquete_id", name=op.f("pk_paquetes")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("paquetes")
    op.drop_table("config")
    # ### end Alembic commands ###
