"""usuarios saldos movimientos auditoria

Revision ID: 11795042fb1b
Revises: 03880c873456
Create Date: 2026-10-08 12:57:21.088081

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "11795042fb1b"
down_revision: str | Sequence[str] | None = "03880c873456"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usuarios",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("usuario", sa.Text(), nullable=False),
        sa.Column("hash_password", sa.Text(), nullable=False),
        sa.Column("rol", sa.Text(), nullable=False),
        sa.Column("debe_cambiar_clave", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("activo", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("ultimo_login", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("rol IN ('admin', 'cliente')", name=op.f("ck_usuarios_rol")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usuarios")),
        sa.UniqueConstraint("usuario", name=op.f("uq_usuarios_usuario")),
    )
    op.create_table(
        "auditoria",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("usuario_id", sa.BigInteger(), nullable=True),
        sa.Column("accion", sa.Text(), nullable=False),
        sa.Column("detalle", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column(
            "fecha", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"], ["usuarios.id"], name=op.f("fk_auditoria_usuario_id_usuarios")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auditoria")),
    )
    op.create_index(op.f("ix_auditoria_fecha"), "auditoria", ["fecha"], unique=False)
    op.create_table(
        "movimientos",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("usuario_id", sa.BigInteger(), nullable=False),
        sa.Column("tipo", sa.Text(), nullable=False),
        sa.Column("monto", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("saldo_disponible_resultante", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("saldo_reservado_resultante", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("pedido_id", sa.BigInteger(), nullable=True),
        sa.Column("nota", sa.Text(), nullable=True),
        sa.Column("creado_por", sa.BigInteger(), nullable=True),
        sa.Column(
            "fecha", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "tipo <> 'ajuste' OR monto <> 0", name=op.f("ck_movimientos_ajuste_no_cero")
        ),
        sa.CheckConstraint(
            "tipo = 'ajuste' OR monto > 0", name=op.f("ck_movimientos_monto_positivo")
        ),
        sa.CheckConstraint(
            "tipo IN ('abono', 'reserva', 'liberacion', 'cargo', 'ajuste')",
            name=op.f("ck_movimientos_tipo"),
        ),
        sa.CheckConstraint(
            "tipo NOT IN ('abono', 'ajuste') OR coalesce(btrim(nota), '') <> ''",
            name=op.f("ck_movimientos_nota_obligatoria"),
        ),
        sa.CheckConstraint(
            "saldo_disponible_resultante >= 0", name=op.f("ck_movimientos_disponible_no_negativo")
        ),
        sa.CheckConstraint(
            "saldo_reservado_resultante >= 0", name=op.f("ck_movimientos_reservado_no_negativo")
        ),
        sa.ForeignKeyConstraint(
            ["creado_por"], ["usuarios.id"], name=op.f("fk_movimientos_creado_por_usuarios")
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"], ["usuarios.id"], name=op.f("fk_movimientos_usuario_id_usuarios")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_movimientos")),
    )
    op.create_index(
        "ix_movimientos_usuario_id_fecha", "movimientos", ["usuario_id", "fecha"], unique=False
    )
    op.create_table(
        "saldos",
        sa.Column("usuario_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "saldo_disponible",
            sa.Numeric(precision=12, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "saldo_reservado", sa.Numeric(precision=12, scale=2), server_default="0", nullable=False
        ),
        sa.CheckConstraint("saldo_disponible >= 0", name=op.f("ck_saldos_disponible_no_negativo")),
        sa.CheckConstraint("saldo_reservado >= 0", name=op.f("ck_saldos_reservado_no_negativo")),
        sa.ForeignKeyConstraint(
            ["usuario_id"], ["usuarios.id"], name=op.f("fk_saldos_usuario_id_usuarios")
        ),
        sa.PrimaryKeyConstraint("usuario_id", name=op.f("pk_saldos")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("saldos")
    op.drop_index("ix_movimientos_usuario_id_fecha", table_name="movimientos")
    op.drop_table("movimientos")
    op.drop_index(op.f("ix_auditoria_fecha"), table_name="auditoria")
    op.drop_table("auditoria")
    op.drop_table("usuarios")
    # ### end Alembic commands ###
