"""pedidos y pedido_eventos

Revision ID: 680a4dfdfe5b
Revises: 00d1f4f97ba9
Create Date: 2026-10-08 13:40:45.266269

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "680a4dfdfe5b"
down_revision: str | Sequence[str] | None = "00d1f4f97ba9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pedidos",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("codigo", sa.Text(), nullable=True),
        sa.Column("usuario_id", sa.BigInteger(), nullable=False),
        sa.Column("paquete_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Text(), nullable=False),
        sa.Column("nickname", sa.Text(), nullable=True),
        sa.Column("precio_costo", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("precio_venta", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("estado", sa.Text(), nullable=False),
        sa.Column("referencia", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("token_idempotencia", sa.Text(), nullable=False),
        sa.Column(
            "creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "estado IN ('CREADO', 'PROCESANDO', 'EXITOSO', 'FALLIDO', 'PENDIENTE_VERIFICAR')",
            name=op.f("ck_pedidos_estado"),
        ),
        sa.CheckConstraint(
            "player_id ~ '^[0-9]{4,20}$'", name=op.f("ck_pedidos_player_id_formato")
        ),
        sa.CheckConstraint(
            "length(token_idempotencia) > 0", name=op.f("ck_pedidos_token_no_vacio")
        ),
        sa.CheckConstraint("precio_costo >= 0", name=op.f("ck_pedidos_precio_costo_no_negativo")),
        sa.CheckConstraint("precio_venta > 0", name=op.f("ck_pedidos_precio_venta_positivo")),
        sa.ForeignKeyConstraint(
            ["paquete_id"], ["paquetes.paquete_id"], name=op.f("fk_pedidos_paquete_id_paquetes")
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"], ["usuarios.id"], name=op.f("fk_pedidos_usuario_id_usuarios")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pedidos")),
        sa.UniqueConstraint("codigo", name=op.f("uq_pedidos_codigo")),
        sa.UniqueConstraint("usuario_id", "token_idempotencia", name="uq_pedidos_usuario_token"),
    )
    op.create_index("ix_pedidos_estado", "pedidos", ["estado"], unique=False)
    op.create_index("ix_pedidos_player_id", "pedidos", ["player_id"], unique=False)
    op.create_index("ix_pedidos_referencia", "pedidos", ["referencia"], unique=False)
    op.create_index(
        "ix_pedidos_usuario_id_creado_en", "pedidos", ["usuario_id", "creado_en"], unique=False
    )
    op.create_table(
        "pedido_eventos",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("pedido_id", sa.BigInteger(), nullable=False),
        sa.Column("estado_anterior", sa.Text(), nullable=True),
        sa.Column("estado_nuevo", sa.Text(), nullable=False),
        sa.Column("detalle", sa.Text(), nullable=True),
        sa.Column("creado_por", sa.BigInteger(), nullable=True),
        sa.Column(
            "fecha", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["creado_por"], ["usuarios.id"], name=op.f("fk_pedido_eventos_creado_por_usuarios")
        ),
        sa.ForeignKeyConstraint(
            ["pedido_id"], ["pedidos.id"], name=op.f("fk_pedido_eventos_pedido_id_pedidos")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pedido_eventos")),
    )
    op.create_index(
        op.f("ix_pedido_eventos_pedido_id"), "pedido_eventos", ["pedido_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_movimientos_pedido_id_pedidos"), "movimientos", "pedidos", ["pedido_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_movimientos_pedido_id_pedidos"), "movimientos", type_="foreignkey")
    op.drop_index(op.f("ix_pedido_eventos_pedido_id"), table_name="pedido_eventos")
    op.drop_table("pedido_eventos")
    op.drop_index("ix_pedidos_usuario_id_creado_en", table_name="pedidos")
    op.drop_index("ix_pedidos_referencia", table_name="pedidos")
    op.drop_index("ix_pedidos_player_id", table_name="pedidos")
    op.drop_index("ix_pedidos_estado", table_name="pedidos")
    op.drop_table("pedidos")
    # ### end Alembic commands ###
