"""alertas

Revision ID: d1971a9d5b68
Revises: 680a4dfdfe5b
Create Date: 2026-10-08 13:56:29.888602

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1971a9d5b68"
down_revision: str | Sequence[str] | None = "680a4dfdfe5b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alertas",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("tipo", sa.Text(), nullable=False),
        sa.Column("mensaje", sa.Text(), nullable=False),
        sa.Column(
            "creada_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("atendida_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("atendida_por", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "tipo IN ('credito_bajo', 'sin_credito', 'cuenta')", name=op.f("ck_alertas_tipo")
        ),
        sa.ForeignKeyConstraint(
            ["atendida_por"], ["usuarios.id"], name=op.f("fk_alertas_atendida_por_usuarios")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alertas")),
    )
    op.create_index(
        "uq_alertas_tipo_activa",
        "alertas",
        ["tipo"],
        unique=True,
        postgresql_where=sa.text("atendida_en IS NULL"),
    )
    # ### end Alembic commands ###
    # Umbral inicial de crédito bajo (RN-11, Q-06 resuelta en CHG-006).
    op.execute(
        "INSERT INTO config (clave, valor) VALUES ('alerta_credito_min', '10.00') "
        "ON CONFLICT (clave) DO NOTHING"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DELETE FROM config WHERE clave = 'alerta_credito_min'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_alertas_tipo_activa",
        table_name="alertas",
        postgresql_where=sa.text("atendida_en IS NULL"),
    )
    op.drop_table("alertas")
    # ### end Alembic commands ###
